default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 100
  workers:
    - queues: ["payments"]
      threads: 2
      processes: <%= ENV.fetch("JOB_PAYMENTS_PROCESSES", 1) %>
      polling_interval: 0.1
    - queues: ["status"]
      threads: 1
      processes: <%= ENV.fetch("JOB_STATUS_PROCESSES", 1) %>
      polling_interval: 0.5

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
